# Generated by Django 6.1 on 2026-08-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCreation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraccount',
            name='balance_gte_0',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='accountLookup',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='encryptedAccountID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='encryptedBalance',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
    ]
