# Generated by Django 6.1 on 2026-08-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BSCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('merkleLeafHash', models.CharField(max_length=64)),
                ('merkleRootHash', models.CharField(max_length=64)),
                ('jsonData', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BSCreation.useraccount')),
            ],
        ),
    ]
